const FIELD_LABEL_CLASSES = 'tw-text-sm tw-font-semibold tw-leading-5 tw-tracking-normal tw-text-slate-700';

export const THEMES = {
  niceMenu: {
    key: 'niceMenu',
    namespace: 'cci-nm',
    componentPrefix: 'cci-nice-menu',
    productLogo: {
      ariaLabel: 'CCI Nice Menu',
      primary: 'CCI Nice',
      secondary: 'Menu',
    },
    border: 'tw-border-cci-nm-border',
    borderBrand: 'tw-border-cci-nm-brand',
    borderBrandBorder: 'tw-border-cci-nm-brandBorder',
    borderImportant: '!tw-border-cci-nm-border',
    borderBrandImportant: '!tw-border-cci-nm-brand',
    borderBrandStrongImportant: 'hover:!tw-border-cci-nm-brandStrong',
    borderBrandBorderImportant: '!tw-border-cci-nm-brandBorder',
    borderActionImportant: '!tw-border-cci-nm-action',
    borderActionBorderImportant: '!tw-border-cci-nm-actionBorder',
    borderActionStrongImportant: 'hover:!tw-border-cci-nm-actionStrong',
    borderDangerBorder: 'tw-border-cci-nm-dangerBorder',
    borderDangerBorderImportant: '!tw-border-cci-nm-dangerBorder',
    borderDangerImportant: '!tw-border-cci-nm-danger',
    bgBrandImportant: '!tw-bg-cci-nm-brand',
    bgBrandStrongImportant: 'hover:!tw-bg-cci-nm-brandStrong',
    bgBrandSoft: 'tw-bg-cci-nm-brandSoft',
    bgBrandSoftImportant: '!tw-bg-cci-nm-brandSoft',
    bgSurfaceSoft: 'tw-bg-cci-nm-surfaceSoft',
    bgActionImportant: '!tw-bg-cci-nm-action',
    bgActionStrongImportant: 'hover:!tw-bg-cci-nm-actionStrong',
    bgActionSoftImportant: '!tw-bg-cci-nm-actionSoft',
    bgDangerBg: 'tw-bg-cci-nm-dangerBg',
    bgDangerBgImportant: 'hover:!tw-bg-cci-nm-dangerBg',
    text: 'tw-text-cci-nm-text',
    textImportant: '!tw-text-cci-nm-text',
    textMuted: 'tw-text-cci-nm-muted',
    textBrand: 'tw-text-cci-nm-brand',
    textBrandHover: 'hover:tw-text-cci-nm-brand',
    textBrandStrong: 'tw-text-cci-nm-brandStrong',
    textBrandStrongHover: 'hover:tw-text-cci-nm-brandStrong',
    textBrandStrongHoverImportant: 'hover:!tw-text-cci-nm-brandStrong',
    textBrandStrongFocusVisibleImportant: 'focus-visible:!tw-text-cci-nm-brandStrong',
    bgBrandSoftHoverImportant: 'hover:!tw-bg-cci-nm-brandSoft',
    bgBrandSoftFocusVisibleImportant: 'focus-visible:!tw-bg-cci-nm-brandSoft',
    textActionText: 'tw-text-cci-nm-actionText',
    textActionTextHover: 'hover:tw-text-cci-nm-actionText',
    textInfoText: 'tw-text-cci-nm-infoText',
    textDanger: 'tw-text-cci-nm-danger',
    textDangerText: 'tw-text-cci-nm-dangerText',
    textDangerHover: 'hover:tw-text-cci-nm-dangerText',
    bgInfoBg: 'tw-bg-cci-nm-infoBg',
    bgActionSoft: 'tw-bg-cci-nm-actionSoft',
    outlineBrand: 'focus-visible:!tw-outline-cci-nm-brand',
    outlineBrandSoft: 'focus:tw-outline-cci-nm-brandSoft focus-visible:tw-outline-cci-nm-brandSoft',
    focusBorderBrand: 'focus:tw-border-cci-nm-brand',
    focusRingBrandSoft: 'focus:tw-ring-cci-nm-brandSoft',
    disabledBorder: 'disabled:!tw-border-cci-nm-border',
    activeTab: 'data-[state=active]:tw-border-cci-nm-brand data-[state=active]:tw-bg-transparent data-[state=active]:tw-text-cci-nm-brandStrong',
    borderInfoBorder: 'tw-border-cci-nm-infoBorder',
    borderActionBorder: 'tw-border-cci-nm-actionBorder',
    fieldLabel: FIELD_LABEL_CLASSES,
  },
  blog: {
    key: 'blog',
    namespace: 'cci-blog',
    componentPrefix: 'cci-blog',
    productLogo: {
      ariaLabel: 'CCI Blog',
      primary: 'CCI',
      secondary: 'Blog',
    },
    border: 'tw-border-cci-blog-border',
    borderBrand: 'tw-border-cci-blog-brand',
    borderBrandBorder: 'tw-border-cci-blog-brandBorder',
    borderImportant: '!tw-border-cci-blog-border',
    borderBrandImportant: '!tw-border-cci-blog-brand',
    borderBrandStrongImportant: 'hover:!tw-border-cci-blog-brandStrong',
    borderBrandBorderImportant: '!tw-border-cci-blog-brandBorder',
    borderActionImportant: '!tw-border-cci-blog-action',
    borderActionBorderImportant: '!tw-border-cci-blog-actionBorder',
    borderActionStrongImportant: 'hover:!tw-border-cci-blog-actionStrong',
    borderDangerBorder: 'tw-border-cci-blog-dangerBorder',
    borderDangerBorderImportant: '!tw-border-cci-blog-dangerBorder',
    borderDangerImportant: '!tw-border-cci-blog-danger',
    bgBrandImportant: '!tw-bg-cci-blog-brand',
    bgBrandStrongImportant: 'hover:!tw-bg-cci-blog-brandStrong',
    bgBrandSoft: 'tw-bg-cci-blog-brandSoft',
    bgBrandSoftImportant: '!tw-bg-cci-blog-brandSoft',
    bgSurfaceSoft: 'tw-bg-cci-blog-surfaceSoft',
    bgActionImportant: '!tw-bg-cci-blog-action',
    bgActionStrongImportant: 'hover:!tw-bg-cci-blog-actionStrong',
    bgActionSoftImportant: '!tw-bg-cci-blog-actionSoft',
    bgDangerBg: 'tw-bg-cci-blog-dangerBg',
    bgDangerBgImportant: 'hover:!tw-bg-cci-blog-dangerBg',
    text: 'tw-text-cci-blog-text',
    textImportant: '!tw-text-cci-blog-text',
    textMuted: 'tw-text-cci-blog-muted',
    textBrand: 'tw-text-cci-blog-brand',
    textBrandHover: 'hover:tw-text-cci-blog-brand',
    textBrandStrong: 'tw-text-cci-blog-brandStrong',
    textBrandStrongHover: 'hover:tw-text-cci-blog-brandStrong',
    textBrandStrongHoverImportant: 'hover:!tw-text-cci-blog-brandStrong',
    textBrandStrongFocusVisibleImportant: 'focus-visible:!tw-text-cci-blog-brandStrong',
    bgBrandSoftHoverImportant: 'hover:!tw-bg-cci-blog-brandSoft',
    bgBrandSoftFocusVisibleImportant: 'focus-visible:!tw-bg-cci-blog-brandSoft',
    textActionText: 'tw-text-cci-blog-actionText',
    textActionTextHover: 'hover:tw-text-cci-blog-actionText',
    textInfoText: 'tw-text-cci-blog-infoText',
    textDanger: 'tw-text-cci-blog-danger',
    textDangerText: 'tw-text-cci-blog-dangerText',
    textDangerHover: 'hover:tw-text-cci-blog-dangerText',
    bgInfoBg: 'tw-bg-cci-blog-infoBg',
    bgActionSoft: 'tw-bg-cci-blog-actionSoft',
    outlineBrand: 'focus-visible:!tw-outline-cci-blog-brand',
    outlineBrandSoft: 'focus:tw-outline-cci-blog-brandSoft focus-visible:tw-outline-cci-blog-brandSoft',
    focusBorderBrand: 'focus:tw-border-cci-blog-brand',
    focusRingBrandSoft: 'focus:tw-ring-cci-blog-brandSoft',
    disabledBorder: 'disabled:!tw-border-cci-blog-border',
    activeTab: 'data-[state=active]:tw-border-cci-blog-brand data-[state=active]:tw-bg-transparent data-[state=active]:tw-text-cci-blog-brandStrong',
    borderInfoBorder: 'tw-border-cci-blog-infoBorder',
    borderActionBorder: 'tw-border-cci-blog-actionBorder',
    fieldLabel: FIELD_LABEL_CLASSES,
  },
  wpCarousel: {
    key: 'wpCarousel',
    namespace: 'cci-wpc',
    componentPrefix: 'cci-wpc',
    productLogo: {
      ariaLabel: 'WP Posts Carousel',
      primary: 'WP Posts',
      secondary: 'Carousel',
    },
    border: 'tw-border-cci-wpc-border',
    borderBrand: 'tw-border-cci-wpc-brand',
    borderBrandBorder: 'tw-border-cci-wpc-brandBorder',
    borderImportant: '!tw-border-cci-wpc-border',
    borderBrandImportant: '!tw-border-cci-wpc-brand',
    borderBrandStrongImportant: 'hover:!tw-border-cci-wpc-brandStrong',
    borderBrandBorderImportant: '!tw-border-cci-wpc-brandBorder',
    borderActionImportant: '!tw-border-cci-wpc-action',
    borderActionBorderImportant: '!tw-border-cci-wpc-actionBorder',
    borderActionStrongImportant: 'hover:!tw-border-cci-wpc-actionStrong',
    borderDangerBorder: 'tw-border-cci-wpc-dangerBorder',
    borderDangerBorderImportant: '!tw-border-cci-wpc-dangerBorder',
    borderDangerImportant: '!tw-border-cci-wpc-danger',
    bgBrandImportant: '!tw-bg-cci-wpc-brand',
    bgBrandStrongImportant: 'hover:!tw-bg-cci-wpc-brandStrong',
    bgBrandSoft: 'tw-bg-cci-wpc-brandSoft',
    bgBrandSoftImportant: '!tw-bg-cci-wpc-brandSoft',
    bgSurfaceSoft: 'tw-bg-cci-wpc-surfaceSoft',
    bgActionImportant: '!tw-bg-cci-wpc-action',
    bgActionStrongImportant: 'hover:!tw-bg-cci-wpc-actionStrong',
    bgActionSoftImportant: '!tw-bg-cci-wpc-actionSoft',
    bgDangerBg: 'tw-bg-cci-wpc-dangerBg',
    bgDangerBgImportant: 'hover:!tw-bg-cci-wpc-dangerBg',
    text: 'tw-text-cci-wpc-text',
    textImportant: '!tw-text-cci-wpc-text',
    textMuted: 'tw-text-cci-wpc-muted',
    textBrand: 'tw-text-cci-wpc-brand',
    textBrandHover: 'hover:tw-text-cci-wpc-brand',
    textBrandStrong: 'tw-text-cci-wpc-brandStrong',
    textBrandStrongHover: 'hover:tw-text-cci-wpc-brandStrong',
    textBrandStrongHoverImportant: 'hover:!tw-text-cci-wpc-brandStrong',
    textBrandStrongFocusVisibleImportant: 'focus-visible:!tw-text-cci-wpc-brandStrong',
    bgBrandSoftHoverImportant: 'hover:!tw-bg-cci-wpc-brandSoft',
    bgBrandSoftFocusVisibleImportant: 'focus-visible:!tw-bg-cci-wpc-brandSoft',
    textActionText: 'tw-text-cci-wpc-actionText',
    textActionTextHover: 'hover:tw-text-cci-wpc-actionText',
    textInfoText: 'tw-text-cci-wpc-infoText',
    textDanger: 'tw-text-cci-wpc-danger',
    textDangerText: 'tw-text-cci-wpc-dangerText',
    textDangerHover: 'hover:tw-text-cci-wpc-dangerText',
    bgInfoBg: 'tw-bg-cci-wpc-infoBg',
    bgActionSoft: 'tw-bg-cci-wpc-actionSoft',
    outlineBrand: 'focus-visible:!tw-outline-cci-wpc-brand',
    outlineBrandSoft: 'focus:tw-outline-cci-wpc-brandSoft focus-visible:tw-outline-cci-wpc-brandSoft',
    focusBorderBrand: 'focus:tw-border-cci-wpc-brand',
    focusRingBrandSoft: 'focus:tw-ring-cci-wpc-brandSoft',
    disabledBorder: 'disabled:!tw-border-cci-wpc-border',
    activeTab: 'data-[state=active]:tw-border-cci-wpc-brand data-[state=active]:tw-bg-transparent data-[state=active]:tw-text-cci-wpc-brandStrong',
    borderInfoBorder: 'tw-border-cci-wpc-infoBorder',
    borderActionBorder: 'tw-border-cci-wpc-actionBorder',
    fieldLabel: FIELD_LABEL_CLASSES,
  },
};

export function resolveTheme(theme = 'niceMenu') {
  return THEMES[theme] || THEMES.niceMenu;
}
